Add badges component
aeshapatel025/Strive_UI pull request #11
Opened 2023-12-26 05:07 UTC by aeshapatel025

Add 2 different types of badges

1) Image Badges
<img width="976" alt="Screenshot 2023-12-26 at 10 25 17 AM" src="https://github.com/aeshapatel025/Strive_UI/assets/152843736/3394c992-c31e-401d-aef1-0e1a9c593fa2">

2) Cart Badges
<img width="1042" alt="Screenshot 2023-12-26 at 10 25 06 AM" src="https://github.com/aeshapatel025/Strive_UI/assets/152843736/155557e7-70fb-422b-9b2d-71e7092b1c58">

- [x] Checking the code is duplicate or not?
- [x]  Is these code has bug
- [ ]  Is code is check by shubhum sir or ankit sir?
- [ ]  Are you going to merge this or not?

2023-12-26 13:43 UTC, tarakhant1297 requested changes
https://ant.design/components/badge follow props name as antd components

2023-12-26 13:43 UTC, tarakhant1297 commented on src/Badges/Badges.js
> +const Badges = ({ type, variant, img, number, colorsEffect }) => {
@aeshapatel025 use same props name as antd

2023-12-26 13:43 UTC, tarakhant1297 commented on src/Badges/Badges.stories.js
> +        number={10}
@aeshapatel025 same as above

2023-12-26 13:43 UTC, tarakhant1297 commented on src/Badges/Badges.stories.js
> +        colorsEffect="primary"
@aeshapatel025 use color props for Customize Badge dot color

2023-12-27 03:32 UTC, aeshapatel025 commented on src/Badges/Badges.js
> +const Badges = ({ type, variant, img, number, colorsEffect }) => {
i have changes it

2023-12-27 03:32 UTC, aeshapatel025 commented on src/Badges/Badges.stories.js
> +        colorsEffect="primary"
changes it

2023-12-27 03:32 UTC, aeshapatel025 commented on src/Badges/Badges.stories.js
> +        number={10}
changes done!

2023-12-27 05:45 UTC, tarakhant1297 requested changes

2023-12-27 05:45 UTC, tarakhant1297 commented on src/Badges/Badges.stories.js
> +        shape="image"
@aeshapatel025 shape should be circle and square

2023-12-27 07:02 UTC, aeshapatel025 commented
https://github.com/aeshapatel025/Strive_UI/pull/14

> Message ID: ***@***.***>
>

2023-12-28 06:25 UTC, ankitadrixus08 approved these changes

2023-12-28 06:25 UTC, ankitadrixus08 commented on src/Badges/Badges.Styled.js
> +            right: -3px;
why in minus here @aeshapatel025

2023-12-28 06:56 UTC, merged