Add Input Component
aeshapatel025/Strive_UI pull request #16
Opened 2023-12-28 07:07 UTC by aeshapatel025

Add Input Component

<img width="1196" alt="Screenshot 2023-12-28 at 12 36 53 PM" src="https://github.com/aeshapatel025/Strive_UI/assets/152843736/c1bfe5da-7204-43aa-a74c-869c720fd84a">

- [x]  Checking the code is duplicate or not?
- [x]  Is these code has bug
- [ ]  Is code is check by shubhum sir or ankit sir or tara ma'am?
- [ ]  Are you going to merge this or not?

2023-12-28 07:12 UTC, ankitadrixus08 commented on src/Input/Input.Styled.js
> +  height: 182px;
may be don't need height here @aeshapatel025

2023-12-28 07:12 UTC, ankitadrixus08 commented on src/Input/Input.Styled.js
> +  width: 800px;
use max width for this with width:100%; @aeshapatel025

2023-12-28 07:12 UTC, ankitadrixus08 commented on src/Input/Input.Styled.js
> +  row-gap: 10px;
why use ro-gap, column-gap here @aeshapatel025

2023-12-28 07:12 UTC, ankitadrixus08 commented on src/Input/Input.Styled.js
> +  height: 77px;
same as above @aeshapatel025

2023-12-28 07:12 UTC, ankitadrixus08 commented on src/Input/Input.stories.js
> +      <Input label="Username*" />
use name, placeholder here @aeshapatel025

2023-12-28 07:13 UTC, ankitadrixus08 commented on src/Input/Input.js
> +      <input type="text" />
need name and placeholder here @aeshapatel025

2023-12-28 08:46 UTC, aeshapatel025 commented on src/Input/Input.js
> +      <input type="text" />
changes done!

2023-12-28 08:47 UTC, aeshapatel025 commented on src/Input/Input.stories.js
> +      <Input label="Username*" />
changes done!

2023-12-28 08:47 UTC, aeshapatel025 commented on src/Input/Input.Styled.js
> +  height: 77px;
changes done

2023-12-28 08:47 UTC, aeshapatel025 commented on src/Input/Input.Styled.js
> +  height: 182px;
yes ! i have removed it!

2023-12-28 08:47 UTC, aeshapatel025 commented on src/Input/Input.Styled.js
> +  width: 800px;
changes done

2023-12-28 08:48 UTC, aeshapatel025 commented on src/Input/Input.Styled.js
> +  row-gap: 10px;
to give gap but i do not need it so i removed it

2023-12-29 03:54 UTC, ankitadrixus08 approved these changes

2023-12-29 05:35 UTC, tarakhant1297 reviewed
@aeshapatel025 https://ant.design/components/input follow this

2023-12-29 05:35 UTC, tarakhant1297 commented on src/Input/Input.Styled.js
> +export const Input_Container_inputs_type = styled.div`
@aeshapatel025 give proper name to this styled component

2023-12-29 05:35 UTC, tarakhant1297 commented on src/Input/Input.js
> +      <label>{label}</label>
@aeshapatel025 we don't put label in input component

2023-12-29 05:35 UTC, tarakhant1297 commented on src/Input/Input.stories.js
> +        color
@aeshapatel025 why you add this

2023-12-29 05:50 UTC, aeshapatel025 commented on src/Input/Input.stories.js
> +        color
ankit sir told me to add

2024-01-01 06:20 UTC, tarakhant1297 requested changes
https://ant.design/components/input not follow pros as antd input how i add prefix and suffix icon input if i want to add

2024-01-01 07:35 UTC, aeshapatel025 commented on src/Input/Input.js
> +      <label>{label}</label>
changes done

2024-01-03 05:37 UTC, tarakhant1297 approved these changes

2024-01-03 09:28 UTC, merged