Add card component
aeshapatel025/Strive_UI pull request #17
Opened 2023-12-29 04:30 UTC by aeshapatel025

Add 5 different kind of card components

1) Simple Card
<img width="710" alt="Screenshot 2023-12-29 at 9 55 02 AM" src="https://github.com/aeshapatel025/Strive_UI/assets/152843736/c9c8bfa5-e3a3-40dd-bf8d-93d7f55ab94f">

2) Badge Card
<img width="766" alt="Screenshot 2023-12-29 at 9 55 10 AM" src="https://github.com/aeshapatel025/Strive_UI/assets/152843736/0e5f33ba-cbb0-435d-93e8-081de2051f4d">

3)Dismiss Card
<img width="649" alt="Screenshot 2023-12-29 at 9 55 20 AM" src="https://github.com/aeshapatel025/Strive_UI/assets/152843736/aa4d3b69-6297-4e34-898c-2b2cd23d9970">

4) Dismiss Card Overlay
<img width="642" alt="Screenshot 2023-12-29 at 9 55 30 AM" src="https://github.com/aeshapatel025/Strive_UI/assets/152843736/d41900bf-352c-416f-b53b-7c6505538ba8">

5) Horizontal Card
<img width="1009" alt="Screenshot 2023-12-29 at 9 55 40 AM" src="https://github.com/aeshapatel025/Strive_UI/assets/152843736/832a4241-dbf6-45e1-9105-d62418322c78">

- [x]  Checking the code is duplicate or not?
- [x]  Is these code has bug
- [ ]  Is code is check by shubhum sir or ankit sir or tara ma'am?
- [ ]  Are you going to merge this or not?

2023-12-29 04:56 UTC, ankitadrixus08 commented on src/Cards/Cards.Styled.js
> +  width: 298px;
use max width @aeshapatel025

2023-12-29 04:56 UTC, ankitadrixus08 commented on src/Cards/Cards.Styled.js
> +  padding: -1px 110px;
why in minus padding we don't use this @aeshapatel025

2023-12-29 04:56 UTC, ankitadrixus08 commented on src/Cards/Cards.Styled.js
> +  font-family: Arial;
why arial font here in other prs you have different font @aeshapatel025

2023-12-29 04:56 UTC, ankitadrixus08 commented on src/Cards/Cards.Styled.js
> +  height: 100vh;
why use vh here @aeshapatel025

2023-12-29 04:56 UTC, ankitadrixus08 commented on src/Cards/Cards.Styled.js
> +    line-height: 19.6px;
give roundup value @aeshapatel025

2023-12-29 04:56 UTC, ankitadrixus08 commented on src/Cards/Cards.Styled.js
> +  height: 129.875px;
not acceptable @aeshapatel025

2023-12-29 04:56 UTC, ankitadrixus08 commented on src/Cards/Cards.Styled.js
> +  width: 695px;
use max-width @aeshapatel025

2023-12-29 04:56 UTC, ankitadrixus08 commented on src/Cards/Cards.Styled.js
> +  height: 109.875px;
remove this @aeshapatel025

2023-12-29 04:56 UTC, ankitadrixus08 commented on src/Cards/Cards.Styled.js
> +    top: -10px;
why in minus @aeshapatel025

2023-12-29 04:56 UTC, ankitadrixus08 commented on src/Cards/Cards.Styled.js
> +    color: rgb(246, 249, 252);
why use this rgb @aeshapatel025

2023-12-29 04:56 UTC, ankitadrixus08 commented on src/Cards/Cards.Styled.js
> +    transition-timing-function: ease;
meaning of this @aeshapatel025

2023-12-29 04:56 UTC, ankitadrixus08 commented on src/Cards/Cards.Styled.js
> +    height: 28.5px;
remove float value @aeshapatel025

2023-12-29 04:56 UTC, ankitadrixus08 commented on src/Cards/Cards.Styled.js
> +  row-gap: 10px;
here we can use gap ? @aeshapatel025

2023-12-29 04:56 UTC, ankitadrixus08 commented on src/Cards/Cards.Styled.js
> +    margin-top: -15px;
why this in minus @aeshapatel025

2023-12-29 04:56 UTC, ankitadrixus08 commented on src/Cards/Cards.Styled.js
> +    margin-top: -7px;
not needed here in minus @aeshapatel025

2023-12-29 05:19 UTC, aeshapatel025 commented on src/Cards/Cards.Styled.js
> +    margin-top: -7px;
yes ! i have remove it

2023-12-29 05:21 UTC, aeshapatel025 commented on src/Cards/Cards.Styled.js
> +    margin-top: -15px;
to add the h2 title there but now i have removed it and change that

2023-12-29 05:22 UTC, aeshapatel025 commented on src/Cards/Cards.Styled.js
> +  row-gap: 10px;
yes! i have remove them and add gap

2023-12-29 05:23 UTC, aeshapatel025 commented on src/Cards/Cards.Styled.js
> +    height: 28.5px;
changes done!

2023-12-29 05:23 UTC, aeshapatel025 commented on src/Cards/Cards.Styled.js
> +  height: 109.875px;
done changes

2023-12-29 05:23 UTC, aeshapatel025 commented on src/Cards/Cards.Styled.js
> +  width: 695px;
done changes !

2023-12-29 05:23 UTC, aeshapatel025 commented on src/Cards/Cards.Styled.js
> +  height: 129.875px;
done changes

2023-12-29 05:23 UTC, aeshapatel025 commented on src/Cards/Cards.Styled.js
> +    line-height: 19.6px;
done changes!

2023-12-29 05:24 UTC, aeshapatel025 commented on src/Cards/Cards.Styled.js
> +  width: 298px;
done changes

2023-12-29 05:27 UTC, aeshapatel025 commented on src/Cards/Cards.Styled.js
> +  padding: -1px 110px;
changes done

2023-12-29 05:27 UTC, aeshapatel025 commented on src/Cards/Cards.Styled.js
> +  font-family: Arial;
changes done

2023-12-29 05:27 UTC, aeshapatel025 commented on src/Cards/Cards.Styled.js
> +  height: 100vh;
i have change it into px

2023-12-29 05:43 UTC, tarakhant1297 requested changes
https://ant.design/components/card follow this for card props

2023-12-29 05:43 UTC, tarakhant1297 commented on src/Cards/Cards.Styled.js
> +export const commonStyled = css`
@aeshapatel025 add prefix styled to styled component

2023-12-29 05:43 UTC, tarakhant1297 commented on src/Cards/Cards.Styled.js
> +export const commonButton = css`
@aeshapatel025 same as above

2023-12-29 05:43 UTC, tarakhant1297 commented on src/Cards/Cards.Styled.js
> +export const CardContainer = styled.div`
@aeshapatel025 add prefix styled

2023-12-29 05:43 UTC, tarakhant1297 commented on src/Cards/Cards.js
> +    <StyledCardComponent unique={unique} textUnique={textUnique}>
@aeshapatel025why you pass `unique` and `textUnique ` props

2023-12-29 05:43 UTC, tarakhant1297 commented on src/Cards/Cards.js
> +  labelText,
@aeshapatel025 give proper props name to card

2023-12-29 06:54 UTC, aeshapatel025 commented on src/Cards/Cards.js
> +  labelText,
Changes done!

2023-12-29 06:54 UTC, aeshapatel025 commented on src/Cards/Cards.js
> +    <StyledCardComponent unique={unique} textUnique={textUnique}>
Changes done!

2023-12-29 06:54 UTC, aeshapatel025 commented on src/Cards/Cards.Styled.js
> +export const CardContainer = styled.div`
changes done!

2023-12-29 06:55 UTC, aeshapatel025 commented on src/Cards/Cards.Styled.js
> +export const commonButton = css`
changes done!

2023-12-29 06:55 UTC, aeshapatel025 commented on src/Cards/Cards.Styled.js
> +export const commonStyled = css`
changes done

2023-12-29 07:03 UTC, aeshapatel025 commented on src/Cards/Cards.Styled.js
> +    top: -10px;
to give it a proper position but done with it

2024-01-01 08:18 UTC, tarakhant1297 requested changes

2024-01-01 08:18 UTC, tarakhant1297 commented on src/Cards/Cards.Styled.js
> +    color: ${theme.cardTextColor};
@aeshapatel025 give proper name to `cardTextColor `

2024-01-01 08:18 UTC, tarakhant1297 commented on src/Cards/Cards.Styled.js
> +  color: ${theme.textColor};
@aeshapatel025 give proper name to textColor

2024-01-01 08:18 UTC, tarakhant1297 commented on src/Input/Input.Styled.js
> +export const Input_Container_inputs_type = styled.div`
@aeshapatel025 give proper name  to `Input_Container_inputs_type `

2024-01-01 12:04 UTC, aeshapatel025 commented on src/Input/Input.Styled.js
> +export const Input_Container_inputs_type = styled.div`
changes done!

2024-01-02 02:57 UTC, aeshapatel025 commented on src/Cards/Cards.Styled.js
> +  color: ${theme.textColor};
changes done!

2024-01-02 06:18 UTC, tarakhant1297 requested changes

2024-01-02 06:18 UTC, tarakhant1297 commented on src/Cards/Cards.Styled.js
> +export const label = styled.div`
@aeshapatel025 add styled prefix

2024-01-02 06:18 UTC, tarakhant1297 commented on src/Cards/Cards.Styled.js
> +export const closeIcon = styled.div`
@aeshapatel025 add styled prefix

2024-01-02 07:47 UTC, aesha-spreadd commented on src/Cards/Cards.Styled.js
> +export const closeIcon = styled.div`
changes done

2024-01-02 07:47 UTC, aeshapatel025 commented on src/Cards/Cards.Styled.js
> +export const label = styled.div`
changes done

2024-01-03 05:38 UTC, tarakhant1297 approved these changes

2024-01-03 09:53 UTC, aeshapatel025 commented
Add Card components

2024-01-03 09:54 UTC, merged