Add navbar components
aeshapatel025/Strive_UI pull request #18
Opened 2023-12-29 04:54 UTC by aeshapatel025

1) Add navbar component

<img width="1075" alt="Screenshot 2023-12-29 at 10 23 37 AM" src="https://github.com/aeshapatel025/Strive_UI/assets/152843736/3f5f3937-6e72-4ac5-b9ea-1d5688dd93a8">

- [x] Checking the code is duplicate or not?
- [x]  Is these code has bug
- [ ]  Is code is check by shubhum sir or ankit sir or tara ma'am?
- [ ]  Are you going to merge this or not?

2023-12-29 05:50 UTC, tarakhant1297 requested changes

2023-12-29 05:50 UTC, tarakhant1297 commented on src/Navbar/Navbar.js
> +                <a href="">Home</a>
@aeshapatel025 all links pass dynamically from stories file

2023-12-29 05:50 UTC, tarakhant1297 commented on src/Navbar/Navbar.js
> +              <Button type="secondary" variant="outlined" text="Login" />
@aeshapatel025 all component in Navbar pass dynamically .

2023-12-29 05:50 UTC, tarakhant1297 commented on src/Navbar/Navbar.Styled.js
> +export const NavbarMainContainer = styled.div`
@aeshapatel025 use prefix styled to all styled component

2024-01-01 04:55 UTC, aeshapatel025 commented on src/Navbar/Navbar.Styled.js
> +export const NavbarMainContainer = styled.div`
changes done!

2024-01-05 05:31 UTC, tarakhant1297 requested changes

2024-01-05 05:31 UTC, tarakhant1297 commented on src/Navbar/Navbar.Styled.js
> +export const NavbarContainer = styled.div`
@aeshapatel025 use styled prefix

2024-01-05 05:31 UTC, tarakhant1297 commented on src/Navbar/Navbar.Styled.js
> +  h2 {
@aeshapatel025 add line above this

2024-01-05 07:18 UTC, ankitadrixus08 approved these changes

2024-01-05 07:18 UTC, ankitadrixus08 commented on src/Navbar/Navbar.Styled.js
> +    font-size: 30px;
you don't need line height here? @aeshapatel025

2024-01-05 09:15 UTC, merged