add Buttons
aeshapatel025/Strive_UI pull request #4
Opened 2023-12-19 07:33 UTC by aeshapatel025

1) add 4 different types of buttons

1) list buttons
<img width="1078" alt="Screenshot 2023-12-19 at 8 17 54 AM" src="https://github.com/aeshapatel025/storybook_component/assets/152843736/8a7a4afe-17c8-4769-aabc-c3b8a494210f">

2) outlined buttons
<img width="1076" alt="Screenshot 2023-12-19 at 8 18 49 AM" src="https://github.com/aeshapatel025/storybook_component/assets/152843736/28c3ffd4-44c9-4add-96dd-878a6e3d9650">

3) text buttons
<img width="1202" alt="Screenshot 2023-12-19 at 8 19 16 AM" src="https://github.com/aeshapatel025/storybook_component/assets/152843736/fbd2705a-8ffa-483f-98a6-5e273dc245a0">

4) icon buttons
<img width="665" alt="Screenshot 2023-12-19 at 8 19 50 AM" src="https://github.com/aeshapatel025/storybook_component/assets/152843736/046fa48f-b272-4fb5-938a-9625bd0a2751">

- [x]  Checking the code is duplicate or not?
- [x]  Are you going to merge this or not?
- []  Is code is very by shubhum sir or ankit sir?

2023-12-20 04:51 UTC, shubham-spreadd requested changes

2023-12-20 04:51 UTC, shubham-spreadd commented on README.md
can you please explain this read me file

2023-12-20 04:51 UTC, shubham-spreadd commented on src/Button/Button.Styled.js
> +  ${css`
```
/* Dynamic styles */
  ${({ type, outline, border, hovers, theme }) => {
    const bgColor = outline ? 'transparent' : theme?.[type];
    const textColor = outline ? theme?.[type] : 'white';
    const borderColor = border ? 'transparent' : theme?.[type];

    return css`
      background-color: ${bgColor};
      color: ${textColor};
      border-color: ${borderColor};

      /* Hover effect for outline buttons */
      ${outline &&
      hovers &&
      css`
        &:hover,
        &:active {
          background-color: ${theme?.[type]};
          color: white;
        }
      `}
    `;
  }}
```

can be manged like this!

2023-12-20 04:51 UTC, shubham-spreadd commented on src/Button/Button.stories.js
> +      outline
outline should be a variant, not a separate prop.

2023-12-20 04:51 UTC, shubham-spreadd commented on src/Button/Button.stories.js
> +      border
same here. border should be managed from varients only.

2023-12-20 04:51 UTC, shubham-spreadd commented on src/Button/Button.stories.js
> +      variant="outlined"
variant will be IconButton for the icon component.

2023-12-20 04:57 UTC, aeshapatel025 commented on src/Button/Button.stories.js
> +      border
Comment resolved

2023-12-20 04:58 UTC, aeshapatel025 commented on src/Button/Button.stories.js
> +      variant="outlined"
Comment resolved

2023-12-20 06:02 UTC, aeshapatel025 commented on src/Button/Button.stories.js
> +      outline
comment resolved

2023-12-20 06:02 UTC, aeshapatel025 commented on src/Button/Button.Styled.js
> +  ${css`
comment resolved

2023-12-20 12:41 UTC, shubham-spreadd requested changes

2023-12-20 12:41 UTC, shubham-spreadd commented on src/Button/Button.Styled.js
> +      : theme?.[type];
avoid nested ternary

2023-12-20 12:41 UTC, shubham-spreadd commented on src/theme.js
> +  horizontalTitle: 'rgb(255, 78, 84)', // Remove the semicolon
I don't think this comment is required.

2023-12-20 13:31 UTC, shubham-spreadd requested changes

2023-12-20 13:31 UTC, shubham-spreadd commented on .gitignore
git ignore is not proper

2023-12-22 11:27 UTC, shubham-spreadd requested changes

2023-12-22 11:27 UTC, shubham-spreadd commented on src/Button/Button.stories.js
> +export const listButton = () => (
function names should be capital

2023-12-25 05:15 UTC, shubham-spreadd approved these changes

2023-12-25 06:18 UTC, merged