Add avatar component
aeshapatel025/Strive_UI pull request #9
Opened 2023-12-26 04:24 UTC by aeshapatel025

Add avatar component
1) Circle avatar
<img width="1166" alt="Screenshot 2023-12-26 at 9 44 55 AM" src="https://github.com/aeshapatel025/Strive_UI/assets/152843736/922781e4-1728-4d7c-883d-35ddea2496fb">

2) Square Avatar
<img width="1027" alt="Screenshot 2023-12-26 at 9 45 07 AM" src="https://github.com/aeshapatel025/Strive_UI/assets/152843736/f215c318-9fbd-428a-b2e0-e3043a56ea6d">

- [x]  Checking the code is duplicate or not?
- [x]  Is these code has bug
- [ ]  Is code is check by shubhum sir or ankit sir?
- [ ]  Are you going to merge this or not?

2023-12-26 04:27 UTC, ankitadrixus08 commented on src/Avatar/Avatar.Styled.js
> +  small: { width: '3.4rem', height: '3.4rem' },
@aeshapatel025 how many px equals to 3.4rem here?

2023-12-26 04:27 UTC, ankitadrixus08 commented on src/Avatar/Avatar.Styled.js
> +  flex-direction: row;
you don't need to give this @aeshapatel025

2023-12-26 04:27 UTC, ankitadrixus08 commented on src/Avatar/Avatar.Styled.js
> +  justify-content: center;
where is align item? you don't need here? @aeshapatel025

2023-12-26 04:27 UTC, ankitadrixus08 commented on src/Avatar/Avatar.Styled.js
> +  flex-direction: row;
same as above @aeshapatel025

2023-12-26 04:40 UTC, aeshapatel025 commented on src/Avatar/Avatar.Styled.js
> +  flex-direction: row;
I have remove it from StyledAvatarComponent

2023-12-26 04:40 UTC, aeshapatel025 commented on src/Avatar/Avatar.Styled.js
> +  small: { width: '3.4rem', height: '3.4rem' },
54.4 px but i have removed it and add px here

2023-12-26 04:41 UTC, aeshapatel025 commented on src/Avatar/Avatar.Styled.js
> +  justify-content: center;
I have remove  display: flex;
  flex-direction: row;
  gap: 1rem;
  justify-content: center; from here and i only put it in the AvatarContainer

2023-12-26 04:42 UTC, aeshapatel025 commented on src/Avatar/Avatar.Styled.js
> +  flex-direction: row;
Add in AvatarContainer
  display: flex;
  flex-direction: row;
  gap: 1rem;
  justify-content: center;
  align-items: center;

2023-12-26 13:36 UTC, tarakhant1297 requested changes

2023-12-26 13:36 UTC, tarakhant1297 commented on src/Avatar/Avatar.Styled.js
> +      border-radius: ${variant === 'square' ? '0.5rem' : '50%'};
@aeshapatel025 use shape insted of variant

2023-12-26 13:36 UTC, tarakhant1297 commented on src/Avatar/Avatar.Styled.js
> +export default StyledAvatarComponent;
@aeshapatel025 remove this empty styled

2023-12-26 13:36 UTC, tarakhant1297 commented on src/Avatar/Avatar.js
> +const Avatar = ({ type, img, variant }) => {
@aeshapatel025 use `size` instead of `type`

2023-12-27 03:12 UTC, ankitadrixus08 approved these changes

2023-12-27 03:15 UTC, merged